switch to git djvulibre since 3.5.24 fails koreader/koreader-base#26
I'm using gcc version 4.6.3 (Debian 4.6.3-1) and git does compile while
version 3.5.24 fails with:

In file included from ../../libdjvu/GContainer.h:67:0,
                 from ../../libdjvu/GContainer.cpp:63:
../../libdjvu/GSmartPointer.h:492:30: error: ‘size_t’ does not name a type
../../libdjvu/GSmartPointer.h:492:37: error: ISO C++ forbids declaration of ‘n’ with no type [-fpermissive]